### ISSUE TITLE
Dynamically changing the editor's language 

### ISSUE THREAD

**Issue by OtchereDev** [CarterLi/vue3-code-mirror#1]
@CarterLi  thank you for this wonderful work but I am trying to build a clone of pastebin.com, so I want to allow the user the opportunity to change the programming language of the editor. I have tried editing your component for some days now but it seems not to accept the new language it still hold the old one which was set in the mounted hook. I would really appreciate it if you can help. Thanks

**Comment by CarterLi** [comment]
Have you ever tried to attach the property `:key` with the value of the language?

**Comment by OtchereDev** [comment]
I tried it but it did not work.... Thanks anyways, I have found my way around it

Can I contribute to your project on the documentation and making it more customizable and resilient??

**Comment by CarterLi** [comment]
Of course
